### ISSUE TITLE
Web Component Card: Landscape analysis

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-next#50]
## Tasks
- [ ] Complete the landscape analysis for the card component in the [Web components landscape analysis spreadsheet](https://docs.google.com/spreadsheets/d/12H_xQBxp7SY_NwCc3R_ZXOiMtkSESZm6e6ysGVCYmx8/edit?gid=166086625#gid=166086625). 
- [x] Create a document with representative code samples from various design systems. Use the [accordion code sample document](https://docs.google.com/document/d/1Vki-Txm4Nmon1Z9ZPeTv2qNG4CwfnlzvVhpACafuUqY/edit#heading=h.fa3sv1ray42g) as a template.

**Comment by amyleadem** [comment]
This issue is on hold until we finalize the spreadsheet structure in https://github.com/uswds/uswds-team/issues/374

**Comment by brunerae** [comment]
Closing as complete
