### ISSUE TITLE
Web Components: Teaming and tooling survey

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-next#98]
After having a Web Components research kickoff meeting and identifying a [list of WC research questions](https://docs.google.com/document/d/18SCMDT93LYzjdRvbPYEiLeyf8ljKGpmZzTOqAo12rig/edit?usp=sharing), we decided that some questions should be answered by surveying USWDS users. We want to get a better sense of where other agency teams are coming from when it comes to team size, resources, and tech stacks they use. This will help inform our Web Component efforts.

**Comment by thisisdano** [comment]
Thank you!
